[workspace]
members = ["projects/*"]
default-members = [
#    "projects/projective",
#    "projects/shape-core",
#    "projects/convex",
]
exclude = [
    "projects/images",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
