[workspace]
members = ["projects/*"]
default-members = [
    "projects/projective",
    "projects/shape-core",
    "projects/shape-svg",
#    "projects/shape-distance",
]
exclude = [
    "projects/images",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
